### ISSUE TITLE
db范例的login漏洞

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#155]
看leaf的db例子里，login时，使用skeleton.Go去读取数据库，如果没有这个账号就创建这个账号。

这里如果并发的话，2个用户，同一时刻发送同样的账号，是应该有可能，出现2个人查找数据库，都返回可新建账号，出现数据覆盖的情况。这种情况，要如何避免？最好有个范例哈

**Comment by name5566** [comment]
不存在的，你再仔细看看代码




            
            
                
                    
                            
                                
                            
                            
                                Guodong Liang
                            
                    
                        
                            
                                    邮箱：name5566@gmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2019年05月06日 10:02，土豆相公 写道： 看leaf的db例子里，login时，使用skeleton.Go去读取数据库，如果没有这个账号就创建这个账号。
这里如果并发的话，2个用户，同一时刻发送同样的账号，是应该有可能，出现2个人查找数据库，都返回可新建账号，出现数据覆盖的情况。这种情况，要如何避免？最好有个范例哈

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/name5566/leaf/issues/155",
"url": "https://github.com/name5566/leaf/issues/155",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by 15951836388** [comment]
是chanrpc 的rpcUserLogin里， accIDUsers[accID]，已经保证了，同样的账号会当做重复登录，会被踢？

**Comment by name5566** [comment]
有多个保障。对的，是会被踢。

**Comment by 15951836388** [comment]
还有，数据库，用了Unique，也能保障
不过这里的逻辑，似乎有些问题。
正常应该是，账号密码正确，通过数据库验证。然后再判断 accIDUsers[accID]是否重复登录。
否则会出现，我玩的好好的。别人用我的账号登录，还没到数据库验证，直接rpcUserLogin就导致我被踢了

**Comment by name5566** [comment]
是先验证账号的
