### ISSUE TITLE
请问leaf消息底层是否封装了消息队列机制

### ISSUE THREAD

**Issue by Neverossa0** [name5566/leaf#64]
目前遇到问题，就是当服务器主动向客户端连续推送2条以上消息（比如连续有2个玩家登录时广播通知其他玩家）时。
客户端有一定几率（并不是每次必现）收到的消息不能解析。主动推送2条不同的消息（比如最后一个玩家登录后，游戏开始。会连续推送玩家登录和游戏开始2条消息）同样会出现这个问题。
逐步排查分析好像是串消息了。
请问leaf底层是否有封装消息队列机制，使用的时候有没有必要重新写一套消息队列机制。

消息发送的源码如下：

//通用的消息广播方法。参考范例和leafwiki写的
func (room *RoomInfo) broadcastRoom(msg interface{}) {

	for _, a := range room.agents {
		a.WriteMsg(msg)
	}
}

//消息send的方法。其他send方法结构与这个类似。
func (room *RoomInfo) sendUpdateRoomMemberRet() {
	players := make([]*pb.PlayerInfo, 0)

	room.sideMap.Range(func(k, v interface{}) bool {
		sider := v.(*mgrSide.SideInfo)
		pbPlayer := sider.GetPlayer().TransToPbPlayerInfo()
		pbPlayer.Side = sider.GetSide().Enum()
		pbPlayer.IsOwner = proto.Bool(sider.GetIsOwner())
		players = append(players, pbPlayer)
		return true
	})
	data := &pb.GS2CUpdateRoomMember{
		Player: players,
	}
	room.broadcastRoom(data)
	log.Debug("反馈房间中玩家列表sendUpdateRoomMemberRet=>房间中有玩家=%v", data)
}

**Comment by name5566** [comment]
Leaf 底层保证了消息有序发送

**Comment by name5566** [comment]
不知道是否有可能是客户端网络层有 bug

**Comment by Neverossa0** [comment]
明白了。谢谢大佬。
我们回头再仔细排查一下客户端。
进一步想问一下，用tcp的话，是否需要做粘包处理呢。

**Comment by name5566** [comment]
需要的，tcp 是流协议




  
  
  


  
    
      
          
            
              
            
            
              Guodong Liang
            
          
            
              
                  邮箱：name5566@gmail.com
              
            
      
    
  


签名由 网易邮箱大师 定制
在2017年12月11日 18:30，Neverossa0 写道： 明白了。谢谢大佬。
我们回头再仔细排查一下客户端。
进一步想问一下，用tcp的话，是否需要做粘包处理呢。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/name5566/leaf","title":"name5566/leaf","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/name5566/leaf"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Neverossa0 in #64: 明白了。谢谢大佬。\r\n我们回头再仔细排查一下客户端。\r\n进一步想问一下，用tcp的话，是否需要做粘包处理呢。"}],"action":{"name":"View Issue","url":"https://github.com/name5566/leaf/issues/64#issuecomment-350684232"}}}

**Comment by Neverossa0** [comment]
明白了。谢谢。
