### ISSUE TITLE
leafserver的例子只能本地（127.0.0.1）调用吗？

### ISSUE THREAD

**Issue by workingGitHub** [name5566/leaf#65]
修改了客户端的实现方法，把127.0.0.1修改为服务器服务IP，发现会无法链接。
working@working-B85M-D2V-TM:~/golang/code/leafserver/src$ clientdemo01
panic: dial tcp 47.95.*.*:3563: getsockopt: connection refused

goroutine 1 [running]:

**Comment by name5566** [comment]
是否和防火墙有关？

在2017年12月12日 22:35，workingGitHub 写道： 修改了客户端的实现方法，把127.0.0.1修改为服务器服务IP，发现会无法链接。
working@working-B85M-D2V-TM:~/golang/code/leafserver/src$ clientdemo01
panic: dial tcp 47.95..:3563: getsockopt: connection refused
goroutine 1 [running]:

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/name5566/leaf","title":"name5566/leaf","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/name5566/leaf"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"leafserver的例子只能本地（127.0.0.1）调用吗？ (#65)"}],"action":{"name":"View Issue","url":"https://github.com/name5566/leaf/issues/65"}}}
