### ISSUE TITLE
[fatal  ] open conf/server.json: no such file or directory

### ISSUE THREAD

**Issue by zzjfengqing** [name5566/leaf#66]
leafserver的例子  装好之后  运行  server出现这样的提示  ，这个server.json在bin下面是存在的。是不是因为我用的mac机的缘故？

**Comment by name5566** [comment]
是否处理好了 workspace，mac 下应该也一样的

在2017年12月19日 16:54，zzj 写道： leafserver的例子  装好之后  运行  server出现这样的提示  ，这个server.json在bin下面是存在的。是不是因为我用的mac机的缘故？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/name5566/leaf","title":"name5566/leaf","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/name5566/leaf"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"[fatal  ] open conf/server.json: no such file or directory (#66)"}],"action":{"name":"View Issue","url":"https://github.com/name5566/leaf/issues/66"}}}

**Comment by zzjfengqing** [comment]
我确认了 我处理好了工作目录   GoPath  和Bin路径都没错   编译爷通的过

**Comment by zzjfengqing** [comment]
啊 解决了   谢谢  的确是少添加了一个workspace

**Comment by zzjfengqing** [comment]
顺便问下  我客户端的数据粘包顺序是  1.数据包长  2.消息序列号  3.数据。    如果这样的话  服务端这边 大概要改哪些地方， 可以统一这样拆包粘包

**Comment by name5566** [comment]
可以参考：https://github.com/name5566/leaf/issues/52，https://github.com/name5566/leaf/issues/26。另外 wiki 上也有一些资料。

**Comment by Fay-Hu** [comment]
我碰到抛上面那个错是因为Permission denied，加下权限就好了，给后面在Mac下遇到这个问题的人提供多一条解决方案。

**Comment by LeomonDream** [comment]
> 啊 解决了 谢谢 的确是少添加了一个workspace

我也遇到了相同的情况，请问添加workspace是什么意思呢？

**Comment by Feiyu123** [comment]
> 



> 啊 解决了 谢谢 的确是少添加了一个workspace

这个workspace怎么添加啊

**Comment by congcong1one** [comment]
我也出现了这个问题。要把生成的可执行文件server放到 /leafserver/bin/ 目录下再运行，或者把项目路径添加到gopath上再重新编译一次，这样server才能找到 /bin/conf/下的server.json文件，才能正常运行。出现这个问题主要是我用的是modules包管理器，项目路径也没添加到gopath上，而生成的可执行文件默认是在 gopath/bin/ 目录下，这就导致了server在/gopath/bin/下找/leafserver/bin/下的/conf/server.json。要解决这个问题，要么把项目路径添加到gopath上，要么直接把生成的可执行文件移到/leafserver/bin/下运行
