### ISSUE TITLE
leaf 的timer和 agent，是否必须手动释放？

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#78]
skeleton.AfterFunc 是否必须要手动stop？
不stop的话，是不是就不会释放？

还有用户断线，也必须要 agent也 close或者destory吧？
agent 的 close不一定能关闭，那残留该如何处理？

**Comment by name5566** [comment]
释放是什么意思？

在2018年05月25日 12:56，土豆相公 写道： rt

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/name5566/leaf/issues/78","url":"https://github.com/name5566/leaf/issues/78","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/name5566/leaf","title":"name5566/leaf","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/name5566/leaf"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"skeleton.AfterFunc 释放必须要手动stop？ (#78)"}],"action":{"name":"View Issue","url":"https://github.com/name5566/leaf/issues/78"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "skeleton.AfterFunc 释放必须要手动stop？ (#78)",
"sections": [
{
"text": "",
"activityTitle": "**土豆相公**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@15951836388",
"facts": [
{
"name": "Repository: ",
"value": "name5566/leaf"
},
{
"name": "Issue #: ",
"value": 78
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"name5566/leaf\",\n\"issueId\": 78,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"name5566/leaf\",\n\"issueId\": 78\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/name5566/leaf/issues/78"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 339048269\n}"
}
],
"themeColor": "26292E"
}

**Comment by 15951836388** [comment]
释放对象

**Comment by name5566** [comment]
不需要的

在2018年05月25日 14:47，土豆相公 写道： 释放对象

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/name5566/leaf/issues/78#issuecomment-391958402","url":"https://github.com/name5566/leaf/issues/78#issuecomment-391958402","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/name5566/leaf","title":"name5566/leaf","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/name5566/leaf"}},"updates":{"snippets":[{"icon":"PERSON","message":"@15951836388 in #78: 释放对象"}],"action":{"name":"View Issue","url":"https://github.com/name5566/leaf/issues/78#issuecomment-391958402"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [name5566/leaf] leaf 的timer和 agent，是否必须手动释放？ (#78)",
"sections": [
{
"text": "",
"activityTitle": "**土豆相公**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@15951836388",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"name5566/leaf\",\n\"issueId\": 78,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"name5566/leaf\",\n\"issueId\": 78\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/name5566/leaf/issues/78#issuecomment-391958402"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 339048269\n}"
}
],
"themeColor": "26292E"
}

**Comment by 15951836388** [comment]
还有用户断线，也必须要 agent 手动执行 close或者destory吗？
agent 的 close不一定能关闭，那万一没有关闭成功 ，残留该如何处理？

**Comment by name5566** [comment]
需要加心跳处理的
